#!/usr/bin/env python3
r"""
Generate the export tables of a proxy build from the system DLL.

    python gen_proxy.py version mpr

For each name writes gen/<name>_exports.h (the functions to forward, used by
proxy.inc) and gen/<name>_x86.def / _x64.def (exports under their real names
and that architecture's ordinals; the system DLL's own forwarders are kept
as forwarders). The 32- and 64-bit system DLLs must export the same names
(ordinals may differ), so one stub table serves both builds. Run again after
adding a name.
"""
import os
import sys

import pefile

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, "gen")
WIN = os.environ.get("SystemRoot", r"C:\Windows")


def exports(path):
    pe = pefile.PE(path, fast_load=True)
    pe.parse_data_directories(directories=[
        pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
    out = []
    for s in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not s.name:
            raise SystemExit("%s: export #%d has no name; not supported" % (path, s.ordinal))
        out.append((s.ordinal, s.name.decode(), s.forwarder.decode() if s.forwarder else None))
    return out


def main():
    os.makedirs(GEN, exist_ok=True)
    for name in sys.argv[1:] or ["version"]:
        tables = {"x86": exports(os.path.join(WIN, "SysWOW64", name + ".dll")),
                  "x64": exports(os.path.join(WIN, "System32", name + ".dll"))}
        shape = {a: sorted((n, f) for _, n, f in t) for a, t in tables.items()}
        if shape["x86"] != shape["x64"]:
            raise SystemExit("%s.dll: 32- and 64-bit export names differ" % name)
        fwd = sorted(n for n, f in shape["x86"] if not f)
        stub = {n: i for i, n in enumerate(fwd)}
        h = ["// Generated by gen_proxy.py from the system %s.dll. Do not edit." % name,
             "#define KP_PROXY_DLL L\"%s.dll\"" % name,
             "const char *const kForwarded[] = {"]
        h += ['    "%s",' % n for n in fwd]
        h += ["};",
              "#define KP_FOR_EACH_STUB(X) " + " ".join("X(%d)" % i for i in range(len(fwd))),
              ""]
        files = [("%s_exports.h" % name, h)]
        for arch, table in tables.items():
            d = ["; Generated by gen_proxy.py from the system %s.dll (%s). Do not edit."
                 % (name, arch), "LIBRARY %s" % name, "EXPORTS"]
            for ordinal, n, f in sorted(table):
                target = f if f else "kp_s%d" % stub[n]
                d.append("    %s = %s @%d" % (n, target, ordinal))
            d.append("")
            files.append(("%s_%s.def" % (name, arch), d))
        for fn, lines in files:
            with open(os.path.join(GEN, fn), "w", newline="\r\n") as f:
                f.write("\n".join(lines))
        print("%s.dll: %d exports, %d stubs" % (name, len(tables["x86"]), len(fwd)))


if __name__ == "__main__":
    main()
